app/Http/Controllers/ProjectController.php, composer.lock, tests/ProjectControllerTest.php
`**READY**`
`NO`
`Changed the flow of posting a project so that its only one function`
`Make sure the test is working and that postProjectCreation function does the job of all three steps`
`noop`
`noop.`
`run phpunit tests/ProjectControllerTest .`
`noop`
=> IWE-42 -- BE: Consolidate project create process to meet new creation flow. One Step Process.

app/Models/Seeking.php, database/migrations/2018_03_14_114624_create_seeking_table.php
`**HOLD**`
`YES`
`Adds model and migration for seeking element.`
`Seeking.php`
`2018_03_14_114624_create_seeking_table.php`
=> IWE-21 BE: Create architecture to add 'Seeking students' including limited types.

app/Contracts/UpdateProjectGeneralContract.php, app/Contracts/VerifyProjectIdContract.php, app/Http/Controllers/ProjectController.php, app/Listeners/Project/UpdateProjectGeneral.php, app/Providers/ProjectServiceProvider.php, app/Services/UpdateProjectGeneralService.php, app/Services/VerifyProjectIdService.php, composer.json, composer.lock, config/database.php, database/migrations/2017_04_21_120716_consolidate_extra_tables_into_attributes_table.php, phpunit.xml, tests/ControllerTests/ProjectControllerTest.php, tests/ListenerTests/UpdateProjectGeneralTest.php
`**READY**`
`NO`
`Changes the UpdateProjectGeneral listener to work with the new event. It also changes somethings in testing in order for database tests to down, but by doing so it reveals how bad are migrations are because they break all our tests`
`Look at the UpdateProjectGeneral listener and make sure it is doing the same thing as before`
`All the other listener refactors and the event refactor`
Run composer install to get dependencies for running future database tests
`There is no way to do this currently due to the migrations being so broken.`
`Event Listener flow`
=> IWE-53 -- BE: Refactor lister for UpdateProjectGeneral to new event data. 

app/Models/Event.php, database/migrations/2018_03_19_103038_create_events_table.php
`**READY**`
`YES`
`Added migration and model for events`
`2018_03_19_103038_create_events_table.php`
`Event.php` model
=> IWE-26 BE: Create architecture to list what (University EVENT) such project is affiliated with.

app/Http/routes.php, app/Models/Member.php, database/migrations/2018_03_21_142301_create_members_table.php, package.json, resources/views/pages/project/create.blade.php
`**READY**`
`YES`
`Created archtiecture for listing members to a project`
`database\migrations\2018_03_21_142301_create_members_table.php`
`\app\Models\Member.php`
=> IWE-19 BE: Create architecture for listing members to a project, including students.

app/Contracts/UpdateProjectPurposeContract.php, app/Http/Controllers/ProjectController.php, app/Providers/ProjectServiceProvider.php, app/Services/UpdateProjectPurposeService.php
`**READY**`
`YES`
`Changes another listener to the contract service flow`
`Look at the files changed and make sure the same logic is done but in a new place`
`All update listener tasks`
`Look at the code since the tests are still broken`t:`
=> IWE-55 -- BE: Refactor lister for UpdateProjectPurpose to new event data. 

app/Contracts/UpdateProjectPolicyContract.php, app/Http/Controllers/ProjectController.php, app/Providers/ProjectServiceProvider.php, app/Services/UpdateProjectPolicyService.php
`**READY**`
`YES`
`Changes another listener to the contract service flow`
`Look at the files changed and make sure the same logic is done but in a new place`
`All update listener tasks`
`Look at the code since the tests are still broken`
=> IWE-54 -- BE: Refactor lister for UpdateProjectPolicy to new event data. 

app/Contracts/UpdateProjectAttributesContract.php, app/Http/Controllers/ProjectController.php, app/Providers/ProjectServiceProvider.php, app/Services/UpdateProjectAttributesService.php
`**READY**`
`YES`
`Changes another listener to the contract service flow`
`Look at the files changed and make sure the same logic is done but in a new place`
`All update listener tasks`
`Look at the code since the tests are still broken`
=> IWE - 52 --  BE: Refactor lister for UpdateProjectAttributes to new event data. 

app/Contracts/GetUniversityEventsContract.php, app/Http/Controllers/ProjectController.php, app/Providers/ProjectServiceProvider.php, app/Services/GetUniversityEventsService.php
`**READY**`
` NO`
`Adds functionality to list what (University EVENT) a project is affiliated with`
`GetUniversityEventService.php`
=> BE: Develop the functionality  to list what (University EVENT) such project is affiliated with.

resources/views/pages/project/create.blade.php
`**READY**`
`NO`
`Replaced default upload button with text & cleaned up code`
`innovation\resources\views\pages\project\create.blade.php`
`Project creation page`
=> IWE-38 -- (Updated) Create updated Project Creation Page

app/Http/Controllers/ProjectController.php, app/Http/Controllers/SearchController.php, app/Listeners/Individual/AddAcademicInterests.php, app/Listeners/Individual/AddInterests.php, app/Listeners/Project/UpdateInterests.php, app/Models/Person.php, app/Models/Project.php, app/Providers/ProjectServiceProvider.php, app/helpers.php, database/factories/ModelFactory.php, resources/views/pages/project/index.blade.php
=> Completed DEV issues.

resources/views/pages/project/create.blade.php, resources/views/pages/welcome/index.blade.php
`**READY**`
`NO`
`Fixed Navbar on Create page, Removed beta text from landing page`
`innovation\resources\views\pages\project\create.blade.php`
=> IWE-62b FE: Fixed Navbar on Create page, Removed beta text from landing page

app/Http/Controllers/AuthController.php, app/Http/Middleware/HelixMiddleware.php, app/Models/Person.php, composer.json, composer.lock, config/app.php, config/dbauth.php, config/ldap.php
`**READY**`
`NO`
`Completed student login functionality`
=> Completed changes with student login

resources/views/layouts/master.blade.php
`**READY**`
`NO`
`Changed Scholarship in top tab to Innovation.`
=> IWE-62b -- (Update) Changed Scholarship to Innovation

app/helpers.php, resources/views/pages/project/create.blade.php
`**READY/HOLD**`
`YES | NO`
`What does this pull request achieve? How does it impact the application.`
`What piece of the code received the most attention and your reviewer should start by looking at?`
`List related PRs against other branches:`
branch | PR
------ | ------
`other_pr_production` | `[link]()`
`Where any changes made to packages or dependencies? Will anything require updating to replicate pull request environment.`
`Outline the steps to test or reproduce the PR here.`
i.e.:
```sh
git pull --prune
git checkout <feature_branch>
bundle; script/server
```
`List general components of the application that this PR will affect:`
=> TMP Change

app/Http/Controllers/InvitationController.php, app/Http/Controllers/ProjectController.php, app/Http/Requests/Project/ProjectCreate.php, app/Models/Project.php, app/Providers/AuthServiceProvider.php, app/Services/CreateTagService.php, app/Services/UpdateCollaboratorsService.php, app/Services/UpdateProjectAttributesService.php, app/Services/UpdateProjectGeneralService.php, app/Services/VerifyProjectIdService.php, public/css/app.css, public/js/collaborators.js, public/js/scripts.js, resources/assets/sass/app.scss, resources/js/collaborators.js, resources/js/scripts.js, resources/views/layouts/partials/display-errors.blade.php, resources/views/pages/project/create.blade.php, resources/views/pages/project/show.blade.php, routes/web.php
`**READY/HOLD**`
`NO`
`Ensures during project create, data is validated.`
`Test wrong data`
`Project Create`
=> IWE-88 Completed Validation on Project create and redirect to proper page

.gitignore, app/Console/Commands/indexDB.php, app/Http/Controllers/ProjectController.php, app/Http/Controllers/SearchController.php, app/Models/Person.php, app/Models/Project.php, composer.json, composer.lock, config/app.php, config/scout.php
`**READY**`
`NO`
`Implements TNTSearch and forces Person model searches to be run with TNTSearch`
`Run Composer install, and index all DB (see command below), Try searching for projects and users.`
`Algolia`
`NEW ENV VALUES`
`Composer Install`
```sh
composer install
php artisan scout:import:all
```
`Search Controller , Laravel Scout`
=> IWE-89 - TNTSearch Implementation for Users.

app/Http/Controllers/ProjectController.php, app/Models/Seeking.php, resources/views/pages/dashboard/events.blade.php, resources/views/pages/project/create.blade.php
`**READY**`
`NO`
`Makes changes in ProjectController to prepare for addition of seeking`
`ProjectController.php`
`Expecting changes to be requested.`
=> IWE:69 BE: Add seeking collaborator based upon user submitted roles

composer.json, composer.lock
`Please update the following env values from Laravel Proxy Pass`
```
PROXY_ACTIVE=true
PROXY_PATH_HEADER=HTTP_X_FORWARDED_PATH
```
=> IWE-84 - Please See ENV Values, For proxy pass issues.

app/Http/Controllers/ProjectController.php, app/Models/Seeking.php, resources/views/pages/dashboard/events.blade.php, resources/views/pages/project/create.blade.php
`**READY**`
`NO`
`Adds seeking table to create project page`
`resources/views/pages/project/create.blade.php`
`Project Create Page`
=> IWE-68 -- FE: Add seeking collaborator based upon user submitted roles. 

app/Http/Controllers/ProjectController.php, app/Models/Seeking.php, resources/views/layouts/partials/project-panel.blade.php, resources/views/pages/dashboard/events.blade.php, resources/views/pages/project/create.blade.php
`**READY**`
`NO`
`Adds if check to see if project creator has a faculty page or not`
`resources/views/layouts/partials/project-panel.blade.php`
=> IWE-87 -- FE: Check to see if a member is a faculty if not disable "See ____ profile's"

.gitignore, app/Http/Controllers/ProjectController.php, resources/views/layouts/partials/filter-selection-and-new-project-button.blade.php, resources/views/pages/project/create.blade.php, resources/views/pages/project/show.blade.php, resources/views/pages/welcome/index.blade.php
`**READY**`
`NO`
`Disables functionality that currently does not work.`
=> IWE-103: Disabled functionality that is not working.
